dist: bionic
addons:
  apt:
    sources:
      #- avsm
      - sourceline: "ppa:avsm/ppa"
    packages:
      - opam

env:
  global:
    - OCAML_VERSION=4.09.0
branches:
  only:
    - master
    - travis_java
    - travis_ocaml

jobs:
  include:
    - language: java
      script:
        - make java_run
    - language: c
      cache:
        directories:
          - $HOME/.opam
      install:
        - opam init -y -n --disable-sandboxing --comp $OCAML_VERSION
        - opam install -y ounit2 core
        - eval $(opam env)
      script:
        - make ocaml_run
